version: '3.9'

services:

  mongo-topapi:
    image: mongo:4.4.6
    container_name: mongo-topapi
    restart:
      always
    ports:
      - 27017:27017
    volumes:
      - ./.mongo:/data/db
    networks:
      - topapi

networks:
  topapi: