version: '3.9'

services:

  top-api:
    build:
      context: .
      dockerfile: Dockerfile
    #image: top-api:latest
    image: ghcr.io/alslapp/purpleschoo-top-api:main
    container_name: top-api
    restart: always
    ports:
      - 3330:3330
    env_file:
      - ./.env.prod
    networks:
      - topapi

networks:
  topapi: